#!/bin/sh
# Load nvm and set PATH for Node.js
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Add Node.js and npm paths
export PATH="$NVM_DIR/versions/node/$(nvm current)/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="./node_modules/.bin:$PATH"

npx lint-staged
